on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: files
          path: out/*
          