on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          mkdir -p out
          pandoc $(ls draft/**/*.md | sort) -V documentclass=report --metadata-file ./metadata.yaml "--from=gfm-implicit_figures+rebase_relative_paths" -t pdf -s -o out/book.pdf
          pandoc $(ls draft/**/*.md | sort) -V documentclass=report --metadata-file ./metadata.yaml "--from=gfm-implicit_figures+rebase_relative_paths" -t epub -s -o out/book.epub
      - uses: actions/upload-artifact@v4
        with:
          name: files
          path: out/*
          